name: app_movil
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Cambié a la versión mínima compatible, asegúrate de que coincida con la versión de Dart que usas

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  # Aquí puedes agregar más dependencias si es necesario

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Puedes agregar activos aquí si los necesitas
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Puedes agregar fuentes personalizadas aquí si las necesitas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
